package-lock.json
=> chore: remove unused package-lock.json

.github/workflows/tests.yml
_Use GitHub provided CI runner._
=> fix: update ci runner

api/ragflow_server.py, intergrations/chatgpt-on-wechat/plugins/__init__.py, management/server/app.py, management/server/database.py, management/server/utils.py, rag/svr/task_executor.py, sdk/python/ragflow_sdk/__init__.py
清理多个文件中的未使用导入和冗余代码，以提高代码的可读性和维护性。主要改动包括移除未使用的模块导入和删除重复的版权声明。
_Briefly describe what this PR aims to solve. Include background context that will help reviewers understand the purpose of the PR._
=> refactor: 移除未使用的导入和冗余代码，修复自动化测试报错

intergrations/chatgpt-on-wechat/plugins/__init__.py
修复自动化测试报错遗留项
- [x ] Refactoring
=> refactor(plugins): 修复自动化测试报错遗留项

.github/workflows/tests.yml, README.md, web/src/components/message-input/index.tsx, web/src/hooks/logic-hooks.ts, web/src/pages/chat/chat-container/index.tsx, web/src/pages/chat/hooks.ts, web/src/pages/chat/share/large.tsx, web/src/pages/chat/shared-hooks.ts, web/src/pages/flow/chat/box.tsx, web/src/pages/flow/chat/hooks.ts, web/src/pages/search/hooks.ts, web/src/pages/search/index.less, web/src/pages/search/index.tsx
在聊天组件中添加了停止输出消息的功能，用户可以在消息生成过程中中断输出。同时，优化了搜索输入框的样式，隐藏了默认的搜索按钮，并替换为自定义的发送和停止按钮。
修改参照：https://github.com/infiniflow/ragflow/pull/6723/files
在聊天组件中添加了停止输出消息的功能，用户可以在消息生成过程中中断输出。同时，优化了搜索输入框的样式，隐藏了默认的搜索按钮，并替换为自定义的发送和停止按钮。
=> feat(chat): 添加停止输出消息功能

docker/docker-compose.yml
移除docker-compose.yml中重复的management-frontend服务配置，简化文件结构并避免端口冲突
=> refactor(docker): 移除重复的management-frontend服务配置

.github/ISSUE_TEMPLATE/feature_request.yml, management/server/clean_all_data.py, management/server/cleanup_minio_buckets.py, management/server/minio_test.py, management/server/routes/__init__.py, management/server/routes/files/routes.py, management/server/services/files/service.py, management/web/src/common/apis/files/index.ts, management/web/src/common/apis/files/type.ts, management/web/src/common/assets/icons/file.svg, management/web/src/pages/file/index.vue, management/web/src/router/index.ts, management/web/types/auto/svg-component-global.d.ts, management/web/types/auto/svg-component.d.ts
新增文件管理模块，包括文件列表展示、下载、删除及批量删除功能。后端新增文件管理相关路由和服务，前端新增文件管理页面及相关API接口。同时新增MinIO存储桶清理脚本，用于清理未使用的存储桶。
=> feat: 管理系统新增文件管理模块

management/server/database.py, management/server/services/files/file_service.py, management/server/services/files/models/__init__.py, management/server/services/files/service.py, management/server/services/teams/service.py, management/server/services/tenants/service.py, management/server/services/users/service.py
将数据库配置从各个服务文件中移除，统一到 `database.py` 中，减少代码重复。
=> refactor(database): 统一数据库配置并移除重复代码

web/src/layouts/components/header/index.less, web/src/layouts/components/right-toolbar/index.less
header css fix
- [√ ] Bug修复(Bug Fix)
=> header css fix

management/server/database.py, management/server/get_minio_image_url.py, management/server/requirements.txt, management/server/services/knowledgebases/service.py, management/web/src/layouts/components/DocumentParseProgress/index.vue, management/web/src/pages/knowledgebase/index.vue, management/web/types/auto/components.d.ts
=> feat:Elasticsearch添加/图片解析保存

management/server/database.py, management/web/src/layouts/components/DocumentParseProgress/index.vue, management/web/src/pages/knowledgebase/index.vue, management/web/src/router/index.ts
=> fix(界面切换显示空白bug): 修复知识库管理时，切换到其它菜单，界面变空白的情况

management/server/services/files/service.py, management/server/services/knowledgebases/document_parser.py, management/server/services/knowledgebases/service.py, management/web/.env.development, management/web/src/layouts/components/DocumentParseProgress/index.vue
增加对word和ppt的支持，需要安装LibreOffice。同时，将文档解析逻辑从 `KnowledgebaseService` 中提取到独立的 `document_parser.py` 模块，以提高代码的可维护性和复用性。同时优化了文件上传和临时文件处理的逻辑，确保资源正确释放。
=> feat(解析文件类型增加): 解析文件增加对word和ppt的支持

api/db/services/dialog_service.py, management/server/routes/knowledgebases/routes.py, management/server/services/knowledgebases/document_parser.py, management/server/services/knowledgebases/service.py, management/web/src/common/apis/kbs/knowledgebase.ts, management/web/src/pages/knowledgebase/index.vue, vllm/model_test.py
在知识库模块中新增了获取和设置系统Embedding配置的API接口，支持动态配置Embedding模型的基础URL、模型名称和API Key。同时，优化了文档解析逻辑，使用系统配置的Embedding模型生成文本块的向量，并将图片与文本块关联存储。
=> feat: 添加系统Embedding配置功能并优化文档解析

management/Dockerfile, management/server/routes/knowledgebases/routes.py, management/server/services/knowledgebases/service.py, management/web/src/common/apis/kbs/document.ts, management/web/src/pages/knowledgebase/index.vue, management/web/types/auto/components.d.ts
新增顺序批量文档解析功能，支持在知识库详情页启动批量解析任务，并通过轮询实时监控任务进度。该功能包括：
1. 后端新增顺序批量解析路由和服务逻辑
2. 前端添加批量解析按钮和进度展示组件
3. 支持后台异步执行批量解析任务
=> feat(知识库): 添加批量文档解析功能

management/server/services/knowledgebases/document_parser.py, management/web/types/auto/components.d.ts
=> fix(document_parser): 修复解析块回溯错位问题

docker/.env, management/server/routes/users/routes.py, management/server/services/knowledgebases/service.py, management/server/services/users/service.py, management/web/src/common/apis/tables/index.ts, management/web/src/pages/user-management/index.vue, management/web/types/auto/components.d.ts
在用户管理页面中新增重置用户密码的功能，包括前端对话框、表单验证、API调用以及后端服务层的密码重置逻辑。同时，更新了用户管理页面的操作列，增加了重置密码按钮，并调整了相关UI样式。
=> feat(用户管理): 添加重置用户密码功能

.gitignore, management/web/src/common/apis/teams/index.ts, management/web/src/pages/team-management/index.vue
在团队管理页面中，调用获取用户列表API时添加size参数以获取所有用户，避免查询时显示不全的问题。
=> fix(团队管理): 修复用户人数>10人时，团队添加成员显示不全问题。

management/server/routes/users/routes.py
=> 创建账号时返回真实的状态

web/src/pages/add-knowledge/components/knowledge-sidebar/index.tsx, web/src/pages/knowledge/index.tsx
=> Refactor：前台系统知识库板面重构

docker/docker-compose.yml, docker/docker-compose_gpu.yml
为了统一环境变量管理，将.env文件添加到docker-compose.yml和docker-compose_gpu.yml配置中，适配修改端口后的数据读取。
=> refactor(docker): 添加.env文件到docker-compose配置中

management/server/routes/files/routes.py, management/server/services/files/service.py, management/server/services/knowledgebases/document_parser.py, management/web/src/common/apis/files/type.ts, management/web/src/pages/file/index.vue
在文件管理模块中，新增了文件列表的排序功能。用户可以根据文件名、大小、类型和创建时间等字段进行升序或降序排序。同时，前端页面也增加了排序相关的UI交互，后端接口支持传递排序字段和排序方式参数。
=> feat(文件管理): 添加文件列表排序功能

management/server/routes/users/routes.py, management/server/services/knowledgebases/document_parser.py, management/server/services/users/service.py, management/web/src/common/apis/tables/type.ts, management/web/src/pages/file/index.vue, management/web/src/pages/user-management/index.vue
=> feat(用户管理): 添加用户列表排序功能并优化文档解析计数逻辑

management/server/routes/knowledgebases/routes.py, management/server/services/knowledgebases/service.py, management/web/src/common/apis/kbs/document.ts, management/web/src/pages/knowledgebase/index.vue
=> feat(知识库管理): 添加文档和文件列表排序功能并优化表格交互

management/server/requirements.txt, management/server/services/knowledgebases/document_parser.py
=> feat(文档解析): 拓展支持文件解析类型：excel、jpg、png、txt、md

management/server/services/knowledgebases/document_parser.py, management/server/services/knowledgebases/service.py, management/web/src/common/apis/kbs/knowledgebase.ts, management/web/src/pages/file/index.vue, management/web/src/pages/knowledgebase/index.vue
=> feat：知识库精细化管理

README.md, management/server/services/knowledgebases/document_parser.py, management/server/services/knowledgebases/service.py, management/server/siliconflow_emb_test.py
=> feat(文档解析): 适配硅基流动平台并优化Embedding配置处理 (#97)

web/src/app.tsx, web/src/components/chunk_image/index.less, web/src/components/chunk_image/index.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/index.less, web/src/pages/add-knowledge/components/knowledge-chunk/index.tsx, web/src/pages/knowledge/index.tsx
=> feat(知识块管理): 实现chunk关联图片预览显示功能

.gitignore, README.md, README_EN.md, bulid_order.txt, docker/.env, management/Dockerfile, management/docker-compose.yml, management/server/database.py, management/server/requirements.txt, web/src/pages/chat/index.tsx
=> refactor: 更新版本至v0.3.0

management/server/services/knowledgebases/document_parser.py, management/server/services/knowledgebases/excel_parser.py
=> 增加公式解析块，重构excel文件解析

api/apps/conversation_app.py, api/db/services/dialog_service.py, api/db/services/write_service.py, web/src/hooks/write-hooks.ts, web/src/pages/write/index.tsx
=> feat(write): 优化文档撰写，修复图像不输出的问题

api/db/services/dialog_service.py, api/db/services/task_service.py, management/web/src/pages/file/index.vue, management/web/types/auto/components.d.ts, pyproject.toml
=> feat(file): 支持文件夹上传

management/server/services/knowledgebases/excel_parser.py
原版解析excel函数只能读取sheet1，而且对于合并的单元格只有第一个单元格有数据，其他的为non
=> 更新解析excel的函数

management/web/src/pages/knowledgebase/index.vue
- 在批量任务状态为"running"时调用 getDocumentList() 方法
- 优化了批量任务处理流程，提高了页面的实时性和准确性
=> refactor(knowledgebase): 在批量任务解析中，增加各文件的状态更新

management/server/services/knowledgebases/__init__.py, management/server/services/knowledgebases/document_parser.py, management/server/services/knowledgebases/service.py
去除没用使用的数据库连接操作
增加setLevel设置logging解决解析时无日志显示
优化删除文档时数据库查询语句
=> 优化逻辑与去除冗余代码

api/apps/conversation_app.py, api/db/services/database.py, api/db/services/write_service.py, docker/.env, management/server/services/knowledgebases/document_parser.py, management/web/src/pages/file/index.vue, web/src/hooks/write-hooks.ts, web/src/pages/write/index.tsx, web/src/utils/api.ts
=> feat: 文档撰写模式增加上传图片功能

api/apps/kb_app.py, web/src/assets/svg/knowledge-images.svg, web/src/constants/knowledge.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-toolbar/index.tsx, web/src/pages/add-knowledge/components/knowledge-images/index.less, web/src/pages/add-knowledge/components/knowledge-images/index.tsx, web/src/pages/add-knowledge/components/knowledge-sidebar/index.tsx, web/src/pages/add-knowledge/constant.ts, web/src/pages/write/index.tsx, web/src/routes.ts, web/src/utils/api.ts
=> feat: 知识库新增图像集显示功能

api/apps/chunk_app.py, api/apps/kb_app.py, web/src/pages/add-knowledge/components/knowledge-chunk/components/image-selector/index.less, web/src/pages/add-knowledge/components/knowledge-chunk/components/image-selector/index.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/index.tsx, web/src/pages/add-knowledge/components/knowledge-images/index.tsx
=> feat: 增加chunk关联图像修改功能

management/web/src/pages/knowledgebase/index.vue
=> fix: 修复后台管理系统中，切换页面后文档勾选记录未保存的问题
